modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="dragontracker"
version="1.0.0"
displayName="Dragon Tracker"
description="Track and locate dragons from Ice and Fire mod with GUI interface and JourneyMap integration"
authors="DragonTracker Team"

[[dependencies.dragontracker]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.dragontracker]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.dragontracker]]
modId="journeymap"
mandatory=false
versionRange="[5.9.0,)"
ordering="AFTER"
side="CLIENT"

[[dependencies.dragontracker]]
modId="iceandfire"
mandatory=false
versionRange="[2.1.0,)"
ordering="AFTER" 
side="BOTH"